### ISSUE TITLE
Station axis

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#68]
Original [issue 68](https://code.google.com/p/pygeode/issues/detail?id=68) created by neishm on 2015-02-05T19:48:52.000Z:

Would be nice to have a &quot;station&quot; axis, for handling ground-based observation data.  The axis values would be the station names, and the auxarrays could contain the associated lat/lon/height for that location.

Example:

&gt;&gt;&gt; print mydata
&lt;Dataset&gt;:
Vars:
  CH4      (time,station)  (223410,12)
  CO2      (time,station)  (223410,12)
Axes:
  time &lt;StandardTime&gt;:  Jan 1, 1988 01:00:00 to Jun 26, 2013 18:00:00 (223410 values)
  station &lt;Station&gt;:  Alert  to Toronto  (12 values)
Global Attributes:
  {}

&gt;&gt;&gt; print mydata.station.values
['Alert' 'Bratts_Lake' 'Candle_Lake' 'Chibougamau' 'East_Trout_Lake'
 'Egbert' 'Estevan_Point' 'Esther' 'Fraserdale' 'Lac_Labiche'
 'Sable_Island' 'Toronto']

&gt;&gt;&gt; print mydata.station.lat
[ 82.45    51.2     53.9833  49.6833  54.35    44.2167  49.5833  51.6825
  49.8833  54.95    43.9333  43.7833]

&gt;&gt;&gt; print mydata.station.lon
[ -62.5167 -104.7    -105.1167  -74.3333 -104.9833  -79.7833 -126.8667
 -110.2603  -81.5667 -112.45    -60.0167  -79.4667]

&gt;&gt;&gt; print mydata(station='Toronto')
&lt;Dataset&gt;:
Vars:
  CH4      (time,station)  (223410,1)
  CO2      (time,station)  (223410,1)
Axes:
  time &lt;StandardTime&gt;:  Jan 1, 1988 01:00:00 to Jun 26, 2013 18:00:00 (223410 values)
  station &lt;Station&gt;:  Toronto 
Global Attributes:
  {}

**Comment by neishm** [comment]
Station axis support added with commit d3ca53287c43323c60515efd92f3656c302f414a.

**Comment by aph42** [comment]
The regression test for this is breaking on me - the station axis in the netcdf file that gets written out is read back in as a NonCoordinateAxis, instead of a Station axis. I think the issue is line 423 of formats/cfmeta, which at present is

`if isinstance(a,DummyAxis) and len(dependencies) > 0:`

it used to (prior to commit 804d419) read

`if cls is DummyAxis and...`

I gather from that commit this was changed to address some case which was breaking the old logic but I don't understand what the issue was; at present if the standard_name attribute of the axis says it should be a station axis, `cls` gets set to `Station` earlier in `decode_cf`, but then gets overridden at this point.

would 

`if issubclass(cls, DummyAxis) and ...`

address the issue that commit 804d419 was meant to fix?

**Comment by neishm** [comment]
Yes, I think that was a typo.  The axis object `a` isn't updated until the end, so it should have been the axis class `cls` that was checked.

**Comment by aph42** [comment]
Ok - have pushed this change; will reclose this issue. (see commit 89b81f1)
