### ISSUE TITLE
Split Axis class into "coordinate" and "non-coordinate" types

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#72]
I'm starting to look at adding a Station axis to PyGeode, but right away I'm having difficulty sub-classing from Axis.  There's an assumption built-in that the axis values are numerical, and are part of some continuous coordinate system.  For instance:
 - there's a "relative tolerance" (rtol) factor when mapping values from one axis to another (map_to).  The code for computing the default value fails miserably for string arrays.
 - checking if two axes are equal (`Axis.__eq__`) uses `numpy.allclose`
 - the plotting routines render all 1D variables as a connected line, where another type of plot like a histogram may be more appropriate (maybe the user can control this with some additional plotting parameters, but this should be automatic).

It would make my life easier if we re-factor some of the logic of the Axis class into two sub-classes: those which act as a coordinate (the default right now), and those which contain some other kind of data which shouldn't be treated numerically.  Perhaps we could make the Axis class the generic class with no assumption about having numerical values, and sub-class that with a Coordinate axis that includes additional logic for using rtol, etc.?

**Comment by aph42** [comment]
One general thought is that this kind of 'category' axis might be more general than just station names, so we might want to just call it that (?).  That being said, what about making the values of the station axis an integer ID, and putting the name (along with lat/lon/whatever else) in the auxiliary arrays?

There would still be an issue in the mapping code because np.allclose is used for checking those as well, but that could be adapted to deal with string values without a major refactor, and there is the str_as_val function (see the overloaded version in CalendarTime) that can be overloaded so that selecting by station name is still straightforward. And if you just wanted to map such axes by the station names alone, can't this be done by overloading map_to?

As for the plotting, there would be the issue of using the station names as labels instead of the integer IDs, but I think again this could be handled with a custom formatting object, like we do with the Time Axis - it would just have to access the relevant auxiliary arrays when producing the tick labels. 

The idea with showvar was that it would be a sort of one-stop shop for these sorts of things, so maybe if one of the axes is a station/category axis it can call an appropriate, more custom plotting routine (instead of vplot or vcontour). I had thought of doing something like this for spherical harmonics axes as well but never got that far. What kind of plot did you have in mind? Clearly a contour plot doesn't make sense, but if there was a 2D variable with one category axis, one option would be a line plot with lines for each station (and a legend?);  or histograms could be done -- this might be appropriate even for higher-dimensional variables, perhaps.

**Comment by neishm** [comment]
I like the idea of putting the station name in an auxiliary array, and having the values be some dummy IDs.  It would allow things to cope when they aren't aware of station names (or strings in general).

In terms of default plotting behaviour, that could be a bit tricky.  For 1D data (just a station/category axis), then a bar graph may be the most appropriate.  However, with a station axis it may also be desired to use a coloured scatter plot overlaid on a map to get a sense of the spatial patterns of the values.  Not sure how to read the user's mind and know what they want, though.  For 2D data (category axis and something else), then maybe a spaghetti-type plot might be best?

I'll try to get a prototype station axis within the next couple of weeks for testing.

**Comment by neishm** [comment]
For reference, the issue for specifically adding a station axis is #68.  I'd merge these two issues together, if I knew how the hell to do that.

**Comment by neishm** [comment]
Non-coordinate axis was added with commit d3ca53287c43323c60515efd92f3656c302f414a.  I set the 'values' array to be dummy coordinates, and put the meaningful coordinate in an auxarray (with the same name as the axis).

A simple test:
```python
  from pygeode.axis import Station
  station_axis = Station(station=['Alert', 'Toronto'], lat=[82.451065, 43.780491], lon=[-62.506771, -79.46801])
  print station_axis
  print station_axis.values   # Returns dummy coordinates
  print station_axis.station  # Returns the meaningful labels
  print station_axis.lat
  print station_axis.lon
  print station_axis(station='Toronto')  # Can slice by label
```

**Comment by neishm** [comment]
Note: Can't yet save/load this type of data through the netcdf interface.  I still need to add some code in cfmeta to deal with this type of axis.

**Comment by aph42** [comment]
I had some thoughts on how the CF metadata is encoded/decoded - basically I think it would be more flexible to put the relevant encoding/decoding into the corresponding axis class. 

I'd like to step back a bit and think about what should go in to a  1.1 release (there are quite a few niggly useability kinds of things that would be really good to clean up - most notably in the plotting routines) but I'm swamped at the moment and probably wont have time for another week or so to do this properly.

**Comment by neishm** [comment]
For the short term, I'm going to try hacking it into `cfmeta` using the guidelines from the [CF conventions for timeseries data](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_orthogonal_multidimensional_array_representation_of_time_series).  It can always be re-factored later, but I'd like to have something functional for a 1.1 release.

**Comment by neishm** [comment]
Saving and loading non-coordinate axes should be implemented in the `station_axis` branch.  Probably there's missing cases and bugs, but the basic functionality should be there.

An example - creating a variable with a non-coordinate axis):
```python
>>> from pygeode.axis import NonCoordinateAxis
>>> from pygeode.timeaxis import StandardTime
>>> from pygeode.var import Var
>>> from pygeode.formats import netcdf
>>> import numpy as np
>>> person = NonCoordinateAxis (person=['Bob','Doug'], height=[160.,180.], eyecolor=['blue','black'],name='person')
>>> time = StandardTime(values=np.arange(10), units='days', startdate={'year':2016,'month':9, 'day':1})
>>> sleep = np.array([7,8,5,9,9,8,6,8,8,6,7,4,9,8,7,8,9,8,7,5],dtype='int32').reshape(10,2)
>>> sleep = Var([time,person], values=sleep, name='sleep', atts={'long_name':'hours of sleep','units':'hours'})
>>> print sleep
```
```
<Var 'sleep'>:
  Shape:  (time,person)  (10,2)
  Axes:
    time <StandardTime>:  Sep 1, 2016 00:00:00 to Sep 10, 2016 00:00:00 (10 values)
    person <NonCoordinateAxis>:  Bob to Doug (2 values)
  Attributes:
    {'units': 'hours', 'long_name': 'hours of sleep'}
  Type:  Var (dtype="int32")
```
Saving to netcdf, and reading back in again:
```python
>>> netcdf.save("sleep.nc", sleep)
>>> f = netcdf.open("sleep.nc")
>>> sleep = f.sleep
>>> print sleep
```
```
<Var 'sleep'>:
  Shape:  (time,person)  (10,2)
  Axes:
    time <StandardTime>:  Sep 1, 2016 00:00:00 to Sep 10, 2016 00:00:00 (10 values)
    person <NonCoordinateAxis>:  Bob to Doug (2 values)
  Attributes:
    {'units': 'hours', 'long_name': 'hours of sleep', 'ancillary_variables':
    'eyecolor person height'}
  Type:  var_newaxes (dtype="int32")
```
Subsetting along the non-coordinate axis:
```python
print sleep(person='Bob')
```
```
<Dataset>:
Vars:
  sleep (time,person)  (10,1)
Axes:
  time <StandardTime>:  Sep 1, 2016 00:00:00 to Sep 10, 2016 00:00:00 (10 values)
  person <NonCoordinateAxis>:  Bob
Global Attributes:
  {'Conventions': 'CF-1.0'}
```

Will try to stamp out any glaring bugs within the next few weeks.  If there are no concerns by then, I'll plan on merging it into the master branch.

**Comment by neishm** [comment]
Merged this into the master branch.

**Comment by aph42** [comment]
just wanted to say this has been useful, and to say i still exist (!). it's been hard to fit in any time for pygeode stuff in the past few months now that i've moved to ncar in boulder. maybe by christmas i'll have some time to focus v1.1

**Comment by neishm** [comment]
No worries.  I haven't exactly been working at light-speed on this end.
