### ISSUE TITLE
Forward difference operator

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#73]
There are some situations where you'd want to compute a simple forward difference, (e.g. how much a field is changing from one model timestep to another).  We already have a 'right' derivative operator, so it should be easy to make a wrapper to it that forces 'dx' to be a simple integer array [0,1,2,3,...].

One question, though is what to call it?  There's already a 'difference' function in the stats module.  Will calling this one 'difference' as well cause a conflict (i.e. are there any plans to hook stats.difference as a Var method?).

**Comment by aph42** [comment]
I've often thought this would be a useful operation as well. I'm pretty sure it could be made rather more general (i.e. so that you could specify more complicated differences) pretty easily too but we can leave that for later. I would also lean towards making a separate implementation from the derivative variable rather than wrapping it, partly for simplicity (we could just get rid of the dx) and partly because I think we might want to generalize it in a different direction from the derivative operation (even though for now it's probably a simple copy-paste-selective deletion). 

I would also like to avoid name conflicts as much as possible - I think the namespace should be as flat as possible and in some of the work on the docs i've been poking away at recently i've come across a few other cases that would benefit from some renaming (I've been meaning to raise those issues but.. well... life.). 

That being said, I don't see hooking up stats.difference as a Var method. What about calling it 'diff' (which is consistent with the analagous numpy function)? Hopefully between that and the fact that it  will be a Var method rather than a pygeode namespace level function it will be clear enough?

**Comment by neishm** [comment]
'diff' sounds like a good name.  For the initial implementation, we could even go with the same parameters of the numpy function (order of difference and axis number).

Eventually we may need an option to specify either a 'right' or 'left' difference, but for now defaulting to a 'right' difference should be sufficient...

**Comment by aph42** [comment]
Has this gotten anywhere? This would be quite useful so it'd be cool to see in 1.1.

**Comment by neishm** [comment]
Haven't revisited this, but I can add it to my to-do list.  Just have to find a quiet day to sit down and work on some of these things...

**Comment by neishm** [comment]
Just pushed a first version of this code.  Still need to work out some minor details, like whether to do name mangling or keep the original name (which I think could be a topic on its own).

**Comment by neishm** [comment]
Closing this issue since the code is in the repository, there have been no complaints, and I don't foresee doing any further modifications in the near future.
